export const translations = {
  en: {
    loginTitle: "Sunriver hotel",
    usernameLabel: "Username",
    passwordLabel: "Password",
    loginButton: "Login",
    loggingIn: "Logging in...",
    loginSuccess: "Login Successful!",
    logoutButton: "Logout",
    invalidCredentialsError: "Invalid username or password.",
    welcomeMessage: "Welcome!",
    thai: "ไทย",
    english: "English",
    
    // Navbar
    navDashboard: "Booking Overview",
    navRoomStatus: "Room Status",
    navStatistics: "Dashboard",
    navCleaning: "Cleaning Status",
    navReceipt: "Receipt",
    logoUploadTooltip: "Click to upload a new logo",

    // Dashboard
    dashboardTitle: "Booking Overview",
    totalRooms: "Total Rooms",
    available: "Available",
    vacant: "Vacant",
    booked: "Booked",
    today: "Today",
    addBooking: "Add Booking",
    loadingBookings: "Loading booking data...",

    // Daily Summary
    checkIns: "Check-ins",
    checkOuts: "Check-outs",
    staying: "Staying",
    noActivity: "No activity for this day.",

    // Booking Modal
    bookingDetails: "Booking Details",
    editBooking: "Edit Booking",
    newBooking: "New Booking",
    customerName: "Customer Name",
    phone: "Phone Number",
    email: "Email",
    address: "Address",
    taxId: "Tax ID / ID Card",
    checkInDate: "Check-in Date",
    checkOutDate: "Check-out Date",
    room: "Room",
    selectRoom: "Select a room",
    pricePerNight: "Price per Night",
    status: "Booking Status",
    deposit: "Deposit",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    deleteBooking: "Delete Booking",
    deleting: "Deleting...",
    deleteConfirm: "Are you sure you want to delete this booking? This action cannot be undone.",
    statuses: {
      'Paid': 'Paid',
      'Deposit': 'Deposit',
      'Unpaid': 'Unpaid'
    },

    // Calendar
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    daysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],

    // Room Status Page
    roomStatusTitle: "Room Status",
    selectDate: "Select Date",
    sortBy: "Sort By:",
    sortByRoomNumber: "Room No.",
    sortByRoomType: "Room Type",
    sortByBedType: "Bed Type",
    statusVacant: "Vacant",
    statusOccupied: "Occupied",
    statusCheckIn: "Check-in",
    statusCheckOut: "Check-out",
    statusTurnover: "Check-out / Check-in",
    
    // Statistics Page
    statisticsTitle: "Statistics Dashboard",
    occupancyStatistics: "Occupancy Statistics",
    roomPopularity: "Room Popularity",
    daily: "Daily",
    monthly: "Monthly",
    yearly: "Yearly",
    filterByRoomType: "Filter by Room Type:",
    allTypes: "All Types",
    totalNightsBooked: "Total Nights Booked",
    selectMonth: "Select Month",

    // Cleaning Status Page
    cleaningStatusTitle: "Room Cleaning Status",
    cleaned: "Cleaned",
    needsCleaning: "Needs Cleaning",
    updateToClean: "Mark as Cleaned",
    confirmCleanTitle: "Confirm Action",
    confirmCleanMessage: "Are you sure you want to mark this room as 'Cleaned'?",
    confirmNeedsCleaningMessage: "Are you sure you want to mark this room as 'Needs Cleaning'?",
    loadingStatuses: "Loading cleaning statuses...",

    // Receipt Page
    receiptTitle: "Receipt / Tax Invoice",
    searchBookings: "Search by name, phone, check-in date, or booking ID...",
    latestBookings: "Latest 10 Bookings",
    searchResults: "Search Results",
    selectBookings: "Select bookings to include in the receipt.",
    noBookingsFound: "No bookings found.",
    paymentDetails: "Payment Details",
    paymentMethod: "Payment Method",
    paymentDate: "Payment Date",
    cash: "Cash",
    transfer: "Bank Transfer",
    createReceipt: "Create Receipt",
    pleaseSelectBookings: "Please select at least one booking.",
    
    // --- New Receipt Template Fields ---
    receipt: "RECEIPT",
    receiptNo: "Receipt No.",
    date: "Date",
    customerInfo: "Customer Name",
    addressInfo: "Address",
    telInfo: "Tel. No.",
    taxIdInfo: "Tax ID",
    description: "Description",
    noOfRooms: "No. of rooms",
    noOfNights: "No. of Nights",
    unitPrice: "Unit price (THB)",
    total: "Total",
    remarks: "Remarks",
    totalAmount: "Total Amount (THB)",
    paymentInfo: "Payment information",
    cashPayment: "Cash",
    transferPayment: "Transfer",
    thb: "THB",
    authorizedSignature: "Authorized Signature",
    print: "Print / Save as PDF",

    hotelInfo: {
      name: "Sunriver Hotel Limited Partnership",
      name_secondary: "Sunriver Hotel",
      address: "215 Moo 1, Apibanbancha Rd, Tha Uthen, Nakhon Phanom 48120",
      phone: "Tel: +66 93-152-9564",
      email: "Email: sunriver.thauthen@gmail.com",
      taxId: "Tax ID: 0483568000055"
    },
  },
  th: {
    loginTitle: "โรงแรมซันริเวอร์",
    usernameLabel: "ชื่อผู้ใช้",
    passwordLabel: "รหัสผ่าน",
    loginButton: "เข้าสู่ระบบ",
    loggingIn: "กำลังเข้าสู่ระบบ...",
    loginSuccess: "เข้าสู่ระบบสำเร็จ!",
    logoutButton: "ออกจากระบบ",
    invalidCredentialsError: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    welcomeMessage: "ยินดีต้อนรับ!",
    thai: "ไทย",
    english: "English",

    // Navbar
    navDashboard: "ภาพรวมการจอง",
    navRoomStatus: "สถานะห้องพัก",
    navStatistics: "Dashboard",
    navCleaning: "สถานะทำความสะอาด",
    navReceipt: "ใบเสร็จ",
    logoUploadTooltip: "คลิกเพื่ออัปโหลดโลโก้ใหม่",

    // Dashboard
    dashboardTitle: "ภาพรวมการจอง",
    totalRooms: "ห้องพักทั้งหมด",
    available: "ว่าง",
    vacant: "ว่าง",
    booked: "ถูกจองแล้ว",
    today: "วันนี้",
    addBooking: "เพิ่มการจอง",
    loadingBookings: "กำลังโหลดข้อมูลการจอง...",

    // Daily Summary
    checkIns: "เช็คอิน",
    checkOuts: "เช็คเอาท์",
    staying: "กำลังเข้าพัก",
    noActivity: "ไม่มีกิจกรรมสำหรับวันนี้",

    // Booking Modal
    bookingDetails: "รายละเอียดการจอง",
    editBooking: "แก้ไขการจอง",
    newBooking: "การจองใหม่",
    customerName: "ชื่อลูกค้า",
    phone: "เบอร์โทรศัพท์",
    email: "อีเมล",
    address: "ที่อยู่",
    taxId: "เลขบัตรประชาชน / เลขผู้เสียภาษี",
    checkInDate: "วันที่เช็คอิน",
    checkOutDate: "วันที่เช็คเอาท์",
    room: "ห้อง",
    selectRoom: "เลือกห้องพัก",
    pricePerNight: "ราคาต่อคืน",
    status: "สถานะการจอง",
    deposit: "เงินมัดจำ",
    save: "บันทึก",
    saving: "กำลังบันทึก...",
    cancel: "ยกเลิก",
    deleteBooking: "ลบการจอง",
    deleting: "กำลังลบ...",
    deleteConfirm: "คุณแน่ใจหรือไม่ว่าต้องการลบการจองนี้? การกระทำนี้ไม่สามารถย้อนกลับได้",
    statuses: {
      'Paid': 'ชำระแล้ว',
      'Deposit': 'มัดจำ',
      'Unpaid': 'ยังไม่ชำระ'
    },
    
    // Calendar
    months: ["มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน", "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม"],
    daysShort: ["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส"],

    // Room Status Page
    roomStatusTitle: "สถานะห้องพัก",
    selectDate: "เลือกวันที่",
    sortBy: "เรียงตาม:",
    sortByRoomNumber: "เลขห้อง",
    sortByRoomType: "ประเภทห้อง",
    sortByBedType: "ประเภทเตียง",
    statusVacant: "ว่าง",
    statusOccupied: "กำลังเข้าพัก",
    statusCheckIn: "เช็คอิน",
    statusCheckOut: "เช็คเอาท์",
    statusTurnover: "เช็คเอาท์ / เช็คอิน",

    // Statistics Page
    statisticsTitle: "Dashboard สถิติ",
    occupancyStatistics: "สถิติการเข้าพัก",
    roomPopularity: "ความนิยมของห้องพัก",
    daily: "รายวัน",
    monthly: "รายเดือน",
    yearly: "รายปี",
    filterByRoomType: "กรองตามประเภทห้อง:",
    allTypes: "ทุกประเภท",
    totalNightsBooked: "จำนวนคืนที่เข้าพักทั้งหมด",
    selectMonth: "เลือกเดือน",

    // Cleaning Status Page
    cleaningStatusTitle: "สถานะการทำความสะอาดห้อง",
    cleaned: "ทำความสะอาดแล้ว",
    needsCleaning: "ยังไม่ทำความสะอาด",
    updateToClean: "เปลี่ยนเป็นทำความสะอาดแล้ว",
    confirmCleanTitle: "ยืนยันการกระทำ",
    confirmCleanMessage: "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนสถานะห้องนี้เป็น 'ทำความสะอาดแล้ว'?",
    confirmNeedsCleaningMessage: "คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนสถานะห้องนี้เป็น 'ยังไม่ทำความสะอาด'?",
    loadingStatuses: "กำลังโหลดสถานะการทำความสะอาด...",

    // Receipt Page
    receiptTitle: "ใบเสร็จรับเงิน / ใบกำกับภาษี",
    searchBookings: "ค้นหาจากชื่อ, เบอร์โทร, วันที่เช็คอิน, หรือรหัสการจอง...",
    latestBookings: "10 รายการล่าสุด",
    searchResults: "ผลการค้นหา",
    selectBookings: "เลือกรายการเพื่อรวมในใบเสร็จ",
    noBookingsFound: "ไม่พบข้อมูลการจอง",
    paymentDetails: "ข้อมูลการชำระเงิน",
    paymentMethod: "วิธีการชำระเงิน",
    paymentDate: "วันที่ชำระเงิน",
    cash: "เงินสด",
    transfer: "โอน",
    createReceipt: "สร้างใบเสร็จ",
    pleaseSelectBookings: "กรุณาเลือกอย่างน้อย 1 รายการ",

    // --- New Receipt Template Fields ---
    receipt: "ใบเสร็จรับเงิน",
    receiptNo: "เลขที่ใบเสร็จ",
    date: "วันที่",
    customerInfo: "ชื่อลูกค้า",
    addressInfo: "ที่อยู่",
    telInfo: "โทรศัพท์",
    taxIdInfo: "เลขที่ผู้เสียภาษี",
    description: "รายการ",
    noOfRooms: "จำนวนห้องพัก",
    noOfNights: "จำนวนวันที่เข้าพัก",
    unitPrice: "ราคาต่อห้อง",
    total: "รวม",
    remarks: "หมายเหตุ",
    totalAmount: "รวมเงินทั้งหมด (บาท)",
    paymentInfo: "ข้อมูลการชำระเงิน",
    cashPayment: "เงินสด",
    transferPayment: "เงินโอน",
    thb: "บาท",
    authorizedSignature: "ผู้มีอำนาจลงนาม",
    print: "พิมพ์ / บันทึกเป็น PDF",
    
    hotelInfo: {
      name: "ห้างหุ้นส่วนจำกัด ซันริเวอร์โฮเทล",
      name_secondary: "Sunriver Hotel",
      address: "215 หมู่ 1 ถนนอภิบาลบัญชา ตำบลท่าอุเทน อำเภอท่าอุเทน จังหวัดนครพนม 48120",
      phone: "โทร: 093-152-9564",
      email: "อีเมล: sunriver.thauthen@gmail.com",
      taxId: "เลขประจำตัวผู้เสียภาษี 0483568000055"
    },
  }
};